- name: create ec2 launch config
  hosts: local
  gather_facts: false
  tasks:
  - name: asg create
    ec2_asg:
      name: project-asg
      launch_config_name: launch_config
      region: us-east-2
      target_group_arns: ['arn:aws:elasticloadbalancing:us-east-2:099690303560:targetgroup/project-TG/97a1edf16eb1882c']
      availability_zones: ['us-east-2a']
      min_size: 1
      max_size: 1
      desired_capacity: 1
      replace_all_instances: yes
      vpc_zone_identifier: ['subnet-06cd510b3e930dbba']
      tags:
        - type: prft_web_server
      wait_for_instances: yes
    register: asg_result
    
  - ec2_remote_facts:
      region: us-east-2
      filters:
        tag:type: "prft_web_server-1"
    register: instance_facts
  
  - name: Add the newly created EC2 instance(s) to the local host group
    lineinfile:  path=/etc/ansible/hosts
                 regexp={{ item.public_ip_address }}
                 insertafter="[asg-group]" line={{ item.public_ip_address }}
    with_items: "{{ instance_facts.instances }}"
 
  - name: Add new instance to perficient host group
    add_host:
         hostname: "{{ item.public_ip_address }}"
         groupname: launched
    with_items: "{{ instance_facts.instances }}"
  - name: Let's wait for SSH to come up. Usually that takes ~10 seconds
    local_action: wait_for
         host={{ item.public_ip_address }}
         port=22
         state=started
    with_items: "{{ instance_facts.instances }}"
  - name: Add tag to Instance(s)
    local_action: ec2_tag resource={{ item.id }} region=us-east-2 state=present
    with_items: "{{ instance_facts.instances }}"
    args:
       tags:
          Name: prft-asg-web
